:PROPERTIES:
:ID:       736262EF-1756-42DB-9947-56C542F23582
:END:
#+title: The Eye of the World Book

* Prologue
The Kinslayer walks around trying to find someone. he is approached by
a dark figure who reminds him of his crimes.

The Kinslayer remembers killing his family and then teleports
somewhere else. He tries to summon some magic.

The Kinslayer summons too much power and a lightning bolt comes down
and hits him. This causes lava to spew 500 feet in the air and the
earth to rise where he stands even higher. Eventually he disintegrates
and all that is left is the mountain of earth where he stood miles
into the sky with lava oozing out. The lava falls off the edge and
splits into a forked river forming an island where the dark figure
stands and says he isn't done with the Kinslayer until the end of time
and he will meet him again.
* Chapter 1 - An Empty Road
** A dark figure appears
A father and son are making their way through some windy
mountains. Their names are Tam and Rand. They are delivering some
apple cider for a festival. Rand notices a cloaked figure following
behind them.

** The dark figure disappears
Rand falls over on a rock and when he looks back the dark rider is
gone. Tam, his father, asks him what happened and he explains about the
rider so they go and search for tracks. Rand remembers his childhood
and how he grew up in these woods.

** Into the village
They make their way into the village. We learn that one of them wins
an archery contest every year by focusing on a flame and the void. He
tried to do that again but his mind was still worried about the dark
figure.

We learn of Rand's love interest named Egwene. Eventually they start
talking to some people and sharing news of the winter storms as they
make their way into the village.

** The trouble-maker and his wife
They come across a trouble maker who starts complaining about the
Women's circle. His wife comes out and tells him to leave the Women's
circle matters alone or he's going to have to cook his own food.

Tam and Rand quickly make their way out of there as to not be
recognized because Tam is a widower and he's always being offered
someone's cousin for marriage.

** Setting up for Bel Tine
They continue to make their way into town and see everyone setting up
for the festivities. Older women setting up the Pole where unmarried
men and women will dance and sing courting each other and the places
where contests will happen during the Bel Tine festivities.
** At the inn
The arrive at the inn and are greeted by the inn keeper, Bran.

** Ill omens
They are met by Cenn at the inn who is speaking of ill omens. He says
The Wisdom won't say when winter will end. His son, Mat, sneaks up and
playfully greets Rand. He says they caught a badger and will set it
loose in the Green to watch the girls run away. He invites Rand but
Rand says he needs to unload the barrels first. Mat then tells him he
saw a figure enter town and it happens to be the dark cloaked figure
Rand saw on the road earlier.

** Considering telling someone
The boys discuss the dark figure more and consider telling someone
about it but decide against it as they figure no one would believe
them. Tam tells the boys that a gleeman is in town and they get
excited to see him.

** Bickering about fireworks
They bicker about the peddler carrying the fireworks not being there
yet and how a gleeman would cheer up everyone in town. The boys then
start carrying the goods into the inn.

* Chapter 2 - Strangers
** Inside the inn
As the boys make their way into the inn they notice the Council
sitting around the fireplace waiting for Tam and Brand to join.

Mistress al'Vere invites the boys to the kitchen so they can get
something to eat.

** Ghost dogs
The boys eat some honeycakes and warm cider as they're moving the
goods into the inn. Mat confesses the blacksmith and his wife are
upset with him for putting flour on some dogs in order to scare the
children; which led to the dogs running into the blacksmith's home and
making a mess.

** The two strangers
One of the young boys, Ewin, comes and tells them that two strangers
arrived in town; a high born lady and her guard. Nynaeve was insulted
when the lady treated her like a child, not knowing she was The
Wisdom.

** The raven atop the inn
The boys make their way out of the inn and feel like they're being
watched. A raven perches atop the inn and cocks its head to stare a
beady eye in their direction. They throw rocks at it unsuccessfully
until Lady Moiraine shows up and the raven flies away.

Lady Moiraine is dressed superbly with real gold and blue hues on her
dress and cloak.

** Hired by the Lady
Lady Moiraine talks to the boys and they inquire why she's in Two
Rivers. She says she's there to study history and that Two Rivers is
an interesting place. The boys are dumbfounded as they believe the
town is just a place with sheep.

Lady Moiraine gives them each a valuable silver piece in exchange for
help with "chores" in the future. The boys are shocked at the value of
the piece she gave them.

The peddler finally arrives in town.

* Chapter 3 - The Peddler
** The peddler shares news
The peddler arrives and starts setting up. Crowds amass around him
asking for wares and news. The Council approaches and eventually the
peddler addresses the crowd telling them of the news around the
world. He explains there is war happening and a Dragon has appeared.

We learn that multiple people have claimed to be the Dragon Born in
the last five years but all were false dragons. Regardless, they
brought a lot of war and death to the world with their claims.

** Who is this Dragon
They question the peddler about the identity of the Dragon. He says he
was told this Dragon can wield the One Power, make walls fall with a
shout, control lightning. We learn that the Aes Sedai are the only
ones powerful enough to defeat him.

The Council takes the peddler into the inn, away from the crowd, to
question him some more.

** Nynaeve overhears
Mat talks about how some say that the Dragon could be the savior of
mankind. Nynaeve overhears and comes over complaining that they
shouldn't speak like that. Mat says it's just something he heard. He
thinks some believe the same but don't speak up in fear of the Aes
Sedai and the Children of the Light.

The boys tell Nynaeve that the peddler is in the inn being questioned
about this Dragon and she makes her way in. Egwene, who was standing
next to Nynaeve, stays behind and moves closer to Rand.

** Inviting Egwene to dance
Egwene and Rand have a conversation where he asks her to dance with
him tomorrow. She agrees but says she can only do it in the afternoon
as she'll be busy in the morning. Rand tells her that even though
she's of marrying age she doesn't have to rush and marry someone. She
agrees and says that Nynaeve has been teaching her the ways of The
Wisdom. This concerned Rand as he was hoping to marry Egwene one day
and he knows that Wisdoms seldom marry.
** Dreams of moving
Egwene tells him that she's thinking of moving to a different village
where her services as Wisdom will be needed. Rand tries to discourage
her but she takes offense to this and starts to walk off.
** Someone else has seen the dark rider
The other boys approach Rand and tell him that Perrin had seen the
dark rider near the blacksmith who acted like he didn't believe
him. Egwene overhears them and says they're being childish for
believing these things.

Just then someone with white hair rushes out of the inn like they're
being chased.

* Chapter 4 - The Gleeman
** The white haired man
The man is the gleeman.

** The gleeman complains
The gleeman steps out of the inn complaining that he had a rough
evening arriving at the end and was treated poorly up until this
moment.

He complains that a small girl tried to hit him with a stick. Egwene
says angrily that he's referring to the Wisdom and the gleeman is
taken aback that such a young women would hold such a position.

** The recruitment
The gleeman recruits Egwene to be his assistant for his show and also
recruits Rand and Perrin to attempt to pick him up in the show but
none will be able to.

** A taste of the show
A crowd begins to gather and the gleeman says he'll give them a taste
of the upcoming show. He somersaults in the air and begins to juggle
some balls. He tells of all the tales he'll reveal when the time
comes.
