:PROPERTIES:
:ID:       D0D10D13-DE88-4F5F-A98B-85AE27579B12
:END:
#+title: The Hobbit Book

* Chapter 2
** Gandalf tricks the trolls
Gandalf tricked the trolls to bicker with each other until sunrise and
they turned to stone. Gandalf and Bilbo freed the dwarves. They found
a door on the side of a mountain and Bilbo had the key which he took
from the trolls. They went inside and grabbed some food and gold
before leaving.

** How Gandalf knew about the trolls
They set out on their journey and Gandalf is questioned on where he
went and how he knew about the trolls. He explains that he went to
scout ahead and met some elves (Elrond's people) from Rivendell who
told him there were 3 trolls along the road. He said he looked back
and saw a fire in the distance and felt like he was needed back to
help.

* Chapter 3 - A Short Rest
** A long journey ahead
They continued on their journey and eventually are left with little
food. They finally see the beginning of The Misty Mountains and Bilbo
asks if that is their destination. But Balin tells him that its not
and they have to get through all of the Misty Mountains and then past
the Wilderlands and even then its a long way from there. Bilbo felt
very tired at that moment.

The continued their path further to find Elrond's house. And they went
very far. They came across many valleys and gullies and bogs.

** Jolly elves
They finally find the right location and start their way
down. Eventually they come to a glade and jolly elves start singing a
silly song. Elves seem to be much more silly creatures in this story
than in the LOTR movies. We learn that dwarves don't like them.

** Crossing the bridge to Elrond's house
The elves lead them to the right path and across a very narrow bridge
which they have to take their horses over. The elves tease them some
more. Eventually they find Elrond's house and spend at least 2 weeks
there. It was a very pleasant stay but they didn't have much else to
say about it.

We learn that Elrond's father existed before written history.

** Elrond identifies swords and runes
Elrond provides his home and care for the group and their mounts. He
identifies 2 swords that they found in the trolls lair which are of
Gondolin origin. One sword belonged to the king of Gondolin.

Elrond then asks for their map and holds it up to the moon light
revealing runes that say, "five feet high the door and three may walk
breast." He explains that these are moon-letters which were written by
dwarves and can only be revealed under the same type of moon and
season they were written under.

Elrond speaks of some more text found by the moon light. It appears to
tell them how to find the key hole. They tale their leave the next
morning.

* Chapter 4 - Over Hill and Under Hill
** A stark difference
They start making their way up the dangerous mountain. Its a stark
contrast to the comforts of Elrond's home.

** The thunderstorm
They get caught in a thunderstorm up in the mountains where giants are
playing games throwing rocks near them. Fili and Kili are sent out to
look for better shelter and they return reporting of a cave nearby.

** Inside the cave
They go to the cave and explore it to make sure its safe. After
confirming, they sit around and talk before going to sleep. Bilbo has
a bad dream about the back of the cave opening up. He wakes up to see
that it really has opened and goblins rush out; six per dwarf. Bilbo
yells and it alerts Gandalf who does magic to attack some of the
goblins but its too late. The creatures make off with the dwarves and
Bilbo through the opening of the cave before it closes off.

** The evil (industrialist?) goblins
The goblins take them deeper into the cave whipping them and singing
songs. The goblins are represented as machine making evil creatures;
perhaps a commentary on industrialism?

** The Great Goblin
The Great Goblin questions the group as to why they were in their
front porch, who they are, and where they are going. Thorin says they
were visiting relatives in the mountains, got caught by a storm, and
took shelter in the cave.

The goblins notice the group carrying the sword of Gondolin and
recognize it as the one who killed many of their people. They sentence
them to death but at that moment the lights go out and great growing
blue smoke fills the space; sending lighting toward the goblins and
making holes in them.

** Gandalf to the rescue
Gandalf shows up, kills the Great Goblin, and the group start running
into the caves. The sword Gandalf is holding is the other sword they
had found which is now glowing. They keep killing goblins as they run
deeper into the caves. Bilbo is slow so the dwarves take turns
carrying him on their shoulders. Eventually, the goblins catch up and
pull Bilbo down to ground where he takes a hard hit and passes out.

* Chapter 5 - Riddles in the Dark
** Waking up in the darkness
Bilbo wakes up in darkness, unable to see anything around him. He
reaches around the floor and finds a ring which he simply puts into
his pocket.

He reaches in his other pocket for his pipe and tobacco, finds them,
but doesn't find anything to light them with. He then finds the
Gondolin dagger he acquired from the troll dwelling.

The dagger glowed faintly so Bilbo could see a bit and he realized it
also meant it was Elvish made and that goblins were not very near.

Bilbo makes his way deeper into the cave and comes across a pool of
water. He dare not enter it for it is unknown what could lurk within.

** Gollum
A creature named Gollum, who refers to himself as "my precious" is
rowing on the lake. He spots Bilbo and approaches him, challenging him
to a game of riddles. If Gollum wins he gets to eat Bilbo but if he
loses he has to show him the way out.

They go back and forth exchanging riddles.

** More riddles
They continue exchanging riddles and eventually Bilbo runs out of
them. He reaches into his pocket and finds the ring.

** The golden ring
Bilbo asks Gollum to guess what is in his pocket. Gollum asks for 3
attempts but, of course, is not able to guess correctly. Bilbo then
tells him to keep his end of the bargain so Gollum says he needs go
grab some things that will help them on their way out.

Gollum searches for a golden ring that is able to turn him
invisible. He uses it for hunting sometimes too. But then Gollum
starts to yell.
** The ring is missing
Gollum realizes his ring is missing. He searches for it everywhere
with no luck in finding it. He then asks Bilbo to tell him what he has
in his pocket, suspecting its his ring.

** Going invisible
Bilbo refuses to answer and Gollum jumps into the water, off his boat,
to chase Bilbo. Bilbo runs away into the darkness and trips. He feels
the ring slip onto his finger and as Gollum passes by him he's
confused as to why he can't be seen.

Gollum worries that Bilbo will try to find a way out with his precious
ring and goblins will catch him; using the ring's power of
invisibility to their advantage and killing him.

** Escaping Gollum
Gollum unknowingly guides Bilbo near the exit trying to look for him
but stops short of where the Goblins tend to be. Bilbo tries to make a
daring escape and jumps over Gollum whose heightened senses perceive
him. But Gollum is unsuccessful in catching him. Bilbo keeps running
but Gollum stops and curses him, calling him a thief. Bilbo finds a
door.

** Escaping the goblins
Bilbo sees goblins by the door and they notice him as well. Somehow
the ring was no longer on his finger. They start rushing him and
instead of pulling out his sword he instinctively reaches in his
pocket, looking for the ring. He goes invisible and the goblins are
taken aback. They start searching for him as he hides behind a
barrel. After some time he braves an escape and swerves between the
goblins toward the door. He tries to slip through a crack left open in
the door but gets stuck, his buttons holding him back. The goblins
notice there is a shadow near the door which motivates Bilbo to push
through, bursting his buttons off his shirt in the attempt. Finally
he's outside.

* Chapter 6 - Out of the frying-pan into the fire
** Finding the crew
Bilbo realizes he's lost on the other side of the Misty Mountains and
he walks around for a bit. Eventually he hears some voices and
realizes its his group of allies. They're looking around for him but
can't see him as he's still wearing the ring of invisibility. He plans
to sneak up on them and reveal himself as a surprise but he overhears
the dwarves saying they should leave him behind. Gandalf angrily
disagrees and says Bilbo is useful to the group and that they should
go back and search for him.

** Bilbo reveals himself
Bilbo reveals himself to the group and they are amazed at his story of
how he escaped. He leaves out the detail of the ring but suspects
Gandalf knows he's hiding something.

** Onwards
Gandalf says the group needs to trek ahead as nightfall is coming and
the goblins will sure try to find them. Bilbo is hungry but they lost
all their supplies in the mountains when they were captured.

** Landslide and the clearing
They continue their way up the mountain and come across a landslide
that nearly takes them out. They manage to escape into the trees. They
came upon a clearing and suddenly the sound of wolves howling grows
closer.

** Hundreds of eyes
They all scramble up into trees but Bilbo is too small to find a
branch. Dorin tries to extend a hand but Bilbo is not able to grab it
so Dorin steps down and allows Bilbo to climb on his back. This helps
Bilbo get onto a branch just as hundreds on eyes appear in the
clearing. The eyes belong to wolves who are now rushing Dorin as he
manages to escape into the tree.

** The Wargs
The wolves are known as Wargs and they station guards at the foot of
Dorin and Bilbo's tree, sniffing for the others. Once they manage to
find all the occupied trees they place guards there as well. Luckily,
Wargs are not able to climb so, for the moment, the group is safe.

There is a great wolf among the creatures who begins speaking to them
in their language.

** Overhearing the plan
We learn, from Gandalf listening to the Wargs talking, that they are
allies of the goblins. They had, along with the goblins, planned a
raid against the humans who are settled in the woods but are surprised
the goblins haven't arrived yet.

** Fire
Gandalf gathers some pine cones and sets them ablaze, throwing them
down into the Wargs and burning them. The Wargs run around yelping and
setting each other on fire.

From far above the Lord of the Eagles is watching, curious what is
happening. He sees the Wargs on fire and goblins marching in their
direction. He calls some other eagles to join him.

The goblins arrive and put out the burning Wargs. Then, they make a
huge fire underneath the dwarves and Gandalf, singing songs and
taunting them.

** Flying out of danger
Gandalf climbs to the top of his tree and the Lord of the Eagles
swoops down and grabs him. The dwarves are also grabbed by eagles and
Bilbo is almost left behind. He manages to grab onto Dori's leg as
they fly away.

Bilbo's arms are about to give out when they reach one of the nests
where he and Dori are placed. Their eagle is told to bring them to the
rest of the group so he does.
** The agreement
When they arrive Gandalf is asking the Lord of the Eagles to take them
as far as they can out of the mountains which the Lord agrees. The
group eat some food and rest for the night.

* Chapter 7 - Queer lodgings
** Flying to the rock
Bilbo wakes up hoping he's at home but remembers he's with the eagles
and the group. He climbs on the back of an eagle and closes his eyes
as they start soaring into the sky.

Eventually, they come to a rock surrounded by a river where they are
dropped off. The eagles give a specific phrase farewell which Gandalf
returns with the correct wording and the group make their way down and
across the river into a cave filled with with pebbles.
** The bear man
They learn that they are going to visit a man who lives at The
Carrock. This man can turn into a bear and shift into other forms. We
learn that Gandalf will soon leave them as he has other pressing
matters to attend to.

We learn that this man is quite particular about not eating meat, he
can talk to animals, and he gets upset easily.

** Meeting two by two
The group makes their way through fields of giant bees and finally
arrives at the edge of some oak trees. Gandalf tells them to come in
twos every five minutes following the way he goes.

Gandalf and Bilbo go first and meet the tall man Beorn. He is
forewarned of their coming by his well groomed horses. Gandalf
introduces himself, saying he is the cousin of Radagast who Beorn
seems to know. Then Gandalf proceeds to tell the story of their
journey as the dwarves enter two by two. At first Beorn is surprised
at how many uninvited guests he's receiving but then finds it comical.

** The whole group arrives
Gandalf continues telling their tale while the dwarves keep coming in
two by two. The interruptions of the arrivals actually makes Beorn
more interested in the story which makes him more accepting of the
visitors.
** Having dinner
After they all arrive they're invited into the house for some
food. Beorn talks to the animals in some language they understand and
they start bringing torches, tables, and chairs for the guests.

They all have food listening to Beorn's stories of the dangers that
lie in the Mirkwood. They're a bit worried because soon they'll have
to cross through there before arriving at their destination.
** Singing dwarves
After, the dwarves start telling stories of their own but Beorn is not
interested. Bilbo dozes off and is woken up by a door banging and
Beorn missing. The dwarves start singing songs into the night.

** The bears in the middle of the night
Bilbo falls asleep but wakes up in the middle of the night hearing
animal sounds outside the house. He remembers that Beorn told them to
not go outside at night under any circumstances. Eventually, he falls
back asleep and wakes up late the next day.
** Where has Gandalf gone
One of the dwarves tells Bilbo he almost missed breakfast so he rushed
to eat, not seeing Gandalf or Beorn anywhere. It isn't until evening
that Gandalf arrives and he's questioned where he's been all day and
where Beorn is.

Gandalf takes his time finishing his supper and smoking some rings out
of his pipe before telling them that he spent all day following bear
tracks. There were a great many tracks outside the house from bears of
all sizes. Eventually, he found some tracks leading out of their
location and followed them. The tracks led past the river and into the
place where they encountered the Wargs. Gandalf couldn't easily cross
the river so he didn't continue following the tracks.
** Beorn returns
That evening Beorn does not return so they all go to sleep but see him
the next morning. Beorn tells them he went to verify their story by
capturing a Goblin and Warg, whose head and hide he hung outside his
home. He learned that the Goblins are still searching for the dwarves
because they killed the Great Goblin. He expresses how impressed he is
and thinks highly of the dwarves for what they've done.

Gandalf takes this opportunity to explain their full plan to Beorn who
commits on supplying them with food and mounts for their journey. He
informs them of what they can and can't eat while traversing the
Mirkwood.

** The journey to the Mirkwood
The group sets off on their journey which takes many days before they
arrive at the Mirkwood. Bilbo notices a bear-shaped shadow following
them which Gandalf confirms is Beorn on the last day of their journey.

Gandalf announces that he has to leave which the group groans
about. He warns them not to stray from the path. The dwarves are upset
that now, at the edge of the Mirkwood, they have to release their
mounts as promised. But Gandalf tells them they better keep their word
because having Beorn as an enemy is a worse fate.

* Chapter 8 - Flies and spiders
** The dark Mirkwood
They make their way into the Mirkwood, a place encased with trees
where sunlight barely enters every so often. The air is thick and
feels like it may suffocate them. They travel for many days and in the
evenings are watched, in the pitch darkness, by red, green, and other
colored eyes.
** The black river
They eat a small amount of rations and hunt a squirrel one day that
ends up tasting terrible. When they're all thirsty they come across a
black river and remember the warning that Beorn gave them not to drink
its water. Thinking on how to cross it Bilbo spots a boat on the other
side.
** Crossing the river
Using a rope with a hook, Fili is able to pull the boat in with some
help. When it comes loose from the other side the dwarves pulling fall
and Bilbo holds on to it before it escapes. Eventually, they're all
able to make their way across, 4 by 4, except the last two dwarves who
are quite heavy and needed to cross on their own.

After making it across a deer leaps out of the woods and into the
black water. Thorin shoots an arrow into the beast and they can hear
it reach the shore and fall over.

** Bombur falls in
Bilbo notices that Bombur fell into the water and was sinking almost
fully, all that could be seen was his hat above the surface. The group
send a hooked rope which Bombur is able to grab but after they pull
him to shore they find him fast asleep.

** The hunt
The group then hears horns and dogs barking in the distance, the
sounds of a hunt, which are followed by deer and their babies entering
the area. Some dwarves loose arrows in the directions of the beasts
but none find their targets. This is unfortunate as that was the last
of their ammunition.

** Traveling the woods
They all make their way into the woods and travel for 4 days, all the
while taking turns carrying the sleeping Bombur. Occasionally, they
hear laughter and voices around them but don't see anyone.

** The climb to see
They enter a valley and ask Bilbo to climb to the top of the tallest
oak tree to try and see a way out of the forest. Bilbo does but sees
no end to the trees. He comes down and the news upsets the group.

** Bombur awakens
They all sleep and eat the last of their rations. In the morning
Bombur awakens, hungry and having forgotten everything after meeting
Bilbo in his home. He tells them all of the wonderful dream he was
having with plenty of food and the group tells him to keep those
details to himself.

** The feast in the woods
They continue in the woods for a while and, now being night time, they
see some lights in the distance. They follow it and come across elves
having a feast. The group's hunger overtakes them and they rush it to
beg for food but the camp goes dark and they're left in pitch
blackness. After some struggle to find each other they decide to rest
until its morning but one of them sees the fire start up again a
distance away. They follow the lights and sounds of laughter and
decide to slowly approach this time but are met with the same fate of
the camp going dark. Once more, they struggle to find each other but
after some time are able to.

A third time they see a campfire and follow it. This time the feast is
large and they decide to send Bilbo in by himself. As Bilbo approaches
the camp goes dark again but now he's left by himself without being
able to find the dwarves.

** A sticky situation
He settles down with his back to a tree deciding to wait until
morning. As he starts to doze off he notices a sticky substance on his
hand and that he can't move his feet. A giant spider crawls over him,
trying to poison him like prey. He pulls how his sword and stabs the
creature in the eyes before slaying it. He decides to name the sword
Sting.

After some time he makes his way through the forest to try and find
the dwarves.

** The juicy captives
He comes to a very dark location in the forest and sees that its thick
with spider webs. He looks up into the trees and sees a mass of
spiders conversing. They talk about the juicy dwarves they've caught
and how they plan on eating them. Bilbo realizes the bulging sacks
hanging from the trees are his dwarf companions.
** Luring the spiders away
Bilbo had not realized but the ring had slipped back on his finger. He
notices a dried up stream nearby and goes to grab some stones to throw
at the spiders. Bilbo is a good shot as he's spent much time playing
throwing and accuracy games. He hits one spider on the head and it
drops dead down to the ground. He throws another stone and it breaks
the web holding up another spider who also plunges to its death.

By now the other spiders are starting to notice him so he makes a plan
to lure them away from the dwarves. He throws stones and sings
antagonizing songs to get their attention. They all start to follow as
he makes his away around and away from them.

** Freeing the dwarves
Bilbo climbs up to what he believes to be the empty tree where the
dwarves are hanging but finds a fat spider guarding them. He uses his
sword to kill it and then frees Fili. They both start freeing the
other dwarves when the spiders approach them. Bilbo's ring is no
longer on his finger so he's no invisible anymore. Several of the
other dwarves are freed as the group prepares for a fight with the
spiders.

** The great battle
The dwarves and Bilbo have a great battle with the spiders but their
numbers are too great so Bilbo devices a plan to use his ring and lure
the spiders away from the others. The dwarves are confused at first at
Bilbo's ability to go invisible but are too busy fighting to discuss
it now.

Bilbo lures the spiders away and kills a great many of them. The
dwarves escape and run into the woods. Bilbo keeps running and
eventually the spiders give up on the chase.

** The rest after
They all meet near one of the fires they had been chasing the night
before. Bilbo is questioned over and over about the ring, Gollum, and
everything that happened until now. They all show him great respect
and some bow toward him. They ask him what his plan is for them to get
out of here but Bilbo stays silent.
** Thorin's capture
We then learn that Thorin was captured by the creatures they were all
chasing who had kept moving their campfires. These creatures are Wood
Elves, related to the High Elves they had met in Elrond's realm but
not as refined. They bring Thorin to a cave which is the palace of
their King who questions Thorin why he and his group were chasing the
King's people.
** The war between the elves and dwarves
Thorin explains they were hungry and only came to beg for food. The
king keeps questioning him and Thorin answers until he's asked why he
was in Mirkwood to begin. Thorin refuses to answer this as he knows
that these elves and dwarves of past had a great war when the dwarves
did some jewelry work for the elves but never received
compensation. The dwarves then took some of the treasure of the elves
justifying it in their minds as a form of payment. The elves didn't
agree with the framing of what they considered theft. So, Thorin kept
his mouth shut about the quest and the group's destination.

Thorin is placed back into a dungeon with the threat that he would
have to stay there until he chooses to answer the questions. But the
elves treat him kindly and feed him.

* Chapter 9 - Barrels out of bond
** Captives
As the group tries to decide which direction they'll go numerous
torches surround them. It's the wood elves here to take them
prisoner. With their hunger and tiredness they almost welcome the
arrest. All but Bilbo, who slipped on his ring and stepped away, are
chained together and made to walk fast through the woods. They come
across a bridge which they cross that leads to the elven king's door.

** The king imprisons them
The prisoners are take into the cave which Bilbo hesitantly
follows. The dwarves are brought to the elven king who questions them
like he did Thorin. Similarly, the dwarves refuse to answer about
their destination and make a case for themselves being hungry and
tired with no ill intentions toward the elves.

The king places them in the prison but away from Thorin, planning on
holding them until they give answers of their quest.
** Bilbo finds Thorin
For a week or two Bilbo learns the layout of the cave and surrounding
areas outside. He manages to find all the prisons where his companions
are held including Thorin. He informs Thorin of what happened,
including the spider incident which makes him respect Bilbo even more.

Thorin gives him a message to send to the others to not reveal their
destination and wait until Bilbo can find a way for them to
escape. After delivering his message Bilbo explores an entrance where
barrels of wine are imported into the cave from the nearby human
settlement.

** The lucky feast
Bilbo decides he can use the entrance to help the dwarves escape. The
elves often send down empty barrels to go back to the human
settlements. He can take advantage of this.

One evening there's a great feast in the cave. The king's butler and
the chief captain drink some of the king's fine wine and fall asleep
after. Bilbo can't believe his luck but acts quickly and takes the
prison keys from the captain.
** Bilbo reveals the plan
He lets out each of the dwarves, finishing with Thorin. Bilbo explains
the plan of escaping down the river which the group doesn't like but
they realize they have no other alternative and may not be so lucky as
to get their hands on the cell keys again.
** Into the barrels
They make their way past the sleeping elves and crawl inside of empty
barrels just in time before the group of elves tasked with pushing the
barrels down into the river arrive. The elves wake up the sleeping
butler and ask him if he's sure these are the barrels that are meant
to go back to the men as they're a bit heavy. The butler assures them
these are the correct barrels so they push them down into the river.
** Alone in the dark
Bilbo was not in one of the barrels so he panics about what to do. In
the end he grabs onto one of the last barrels and plunges into the ice
cold water below. The elves close the trap door and leave him and his
floating friends down in the dark waters.

** Down the river
They make their way down the river and eventually the barrels are
gathered by a small village that night. Bilbo makes it to shore,
stealing some supplies from the inhabitants and sleeping until
morning. He's sneezing and feeling cold from his time in the
water. The next morning the barrels are roped together by the
raft-elves and pushed along the river which Bilbo joins again.

* Chapter 10 -  A warm welcome
** The great lake
The river opened up into a great lake where men lived near the
shoreline in a few huts. The men and elves greeted each other and went
to feast together.

** Freeing the dwarves
Bilbo frees Thorin from his barrel and he rolls out in pain and
bruised. After some time he helps Bilbo free the other dwarves. Fili
and Kili were inside apple barrels and come out complaining of the
smell, saying they could eat anything at the moment except any apples.

The group makes their way to the settlement nearby and ask to be taken
to the Master of the town. The guards question them and Thorin
explains he's the son of a king.
