:PROPERTIES:
:ID:       D0D10D13-DE88-4F5F-A98B-85AE27579B12
:END:
#+title: The Hobbit Book

* Chapter 2
** Gandalf tricks the trolls
Gandalf tricked the trolls to bicker with each other until sunrise and
they turned to stone. Gandalf and Bilbo freed the dwarves. They found
a door on the side of a mountain and Bilbo had the key which he took
from the trolls. They went inside and grabbed some food and gold
before leaving.

** How Gandalf knew about the trolls
They set out on their journey and Gandalf is questioned on where he
went and how he knew about the trolls. He explains that he went to
scout ahead and met some elves (Elrond's people) from Rivendell who
told him there were 3 trolls along the road. He said he looked back
and saw a fire in the distance and felt like he was needed back to
help.

* Chapter 3 - A Short Rest
** A long journey ahead
They continued on their journey and eventually are left with little
food. They finally see the beginning of The Misty Mountains and Bilbo
asks if that is their destination. But Balin tells him that its not
and they have to get through all of the Misty Mountains and then past
the Wilderlands and even then its a long way from there. Bilbo felt
very tired at that moment.

The continued their path further to find Elrond's house. And they went
very far. They came across many valleys and gullies and bogs.

** Jolly elves
They finally find the right location and start their way
down. Eventually they come to a glade and jolly elves start singing a
silly song. Elves seem to be much more silly creatures in this story
than in the LOTR movies. We learn that dwarves don't like them.

** Crossing the bridge to Elrond's house
The elves lead them to the right path and across a very narrow bridge
which they have to take their horses over. The elves tease them some
more. Eventually they find Elrond's house and spend at least 2 weeks
there. It was a very pleasant stay but they didn't have much else to
say about it.

We learn that Elrond's father existed before written history.

** Elrond identifies swords and runes
Elrond provides his home and care for the group and their mounts. He
identifies 2 swords that they found in the trolls lair which are of
Gondolin origin. One sword belonged to the king of Gondolin.

Elrond then asks for their map and holds it up to the moon light
revealing runes that say, "five feet high the door and three may walk
breast." He explains that these are moon-letters which were written by
dwarves and can only be revealed under the same type of moon and
season they were written under.

Elrond speaks of some more text found by the moon light. It appears to
tell them how to find the key hole. They tale their leave the next
morning.

* Chapter 4 - Over Hill and Under Hill
** A stark difference
They start making their way up the dangerous mountain. Its a stark
contrast to the comforts of Elrond's home.

** The thunderstorm
They get caught in a thunderstorm up in the mountains where giants are
playing games throwing rocks near them. Fili and Kili are sent out to
look for better shelter and they return reporting of a cave nearby.

** Inside the cave
They go to the cave and explore it to make sure its safe. After
confirming, they sit around and talk before going to sleep. Bilbo has
a bad dream about the back of the cave opening up. He wakes up to see
that it really has opened and goblins rush out; six per dwarf. Bilbo
yells and it alerts Gandalf who does magic to attack some of the
goblins but its too late. The creatures make off with the dwarves and
Bilbo through the opening of the cave before it closes off.

** The evil (industrialist?) goblins
The goblins take them deeper into the cave whipping them and singing
songs. The goblins are represented as machine making evil creatures;
perhaps a commentary on industrialism?

** The Great Goblin
The Great Goblin questions the group as to why they were in their
front porch, who they are, and where they are going. Thorin says they
were visiting relatives in the mountains, got caught by a storm, and
took shelter in the cave.

The goblins notice the group carrying the sword of Gondolin and
recognize it as the one who killed many of their people. They sentence
them to death but at that moment the lights go out and great growing
blue smoke fills the space; sending lighting toward the goblins and
making holes in them.

** Gandalf to the rescue
Gandalf shows up, kills the Great Goblin, and the group start running
into the caves. The sword Gandalf is holding is the other sword they
had found which is now glowing. They keep killing goblins as they run
deeper into the caves. Bilbo is slow so the dwarves take turns
carrying him on their shoulders. Eventually, the goblins catch up and
pull Bilbo down to ground where he takes a hard hit and passes out.

* Chapter 5 - Riddles in the Dark
** Waking up in the darkness
Bilbo wakes up in darkness, unable to see anything around him. He
reaches around the floor and finds a ring which he simply puts into
his pocket.

He reaches in his other pocket for his pipe and tobacco, finds them,
but doesn't find anything to light them with. He then finds the
Gondolin dagger he acquired from the troll dwelling.

The dagger glowed faintly so Bilbo could see a bit and he realized it
also meant it was Elvish made and that goblins were not very near.

Bilbo makes his way deeper into the cave and comes across a pool of
water. He dare not enter it for it is unknown what could lurk within.

** Gollum
A creature named Gollum, who refers to himself as "my precious" is
rowing on the lake. He spots Bilbo and approaches him, challenging him
to a game of riddles. If Gollum wins he gets to eat Bilbo but if he
loses he has to show him the way out.

They go back and forth exchanging riddles.

** More riddles
They continue exchanging riddles and eventually Bilbo runs out of
them. He reaches into his pocket and finds the ring.

** The golden ring
Bilbo asks Gollum to guess what is in his pocket. Gollum asks for 3
attempts but, of course, is not able to guess correctly. Bilbo then
tells him to keep his end of the bargain so Gollum says he needs go
grab some things that will help them on their way out.

Gollum searches for a golden ring that is able to turn him
invisible. He uses it for hunting sometimes too. But then Gollum
starts to yell.
** The ring is missing
Gollum realizes his ring is missing. He searches for it everywhere
with no luck in finding it. He then asks Bilbo to tell him what he has
in his pocket, suspecting its his ring.

** Going invisible
Bilbo refuses to answer and Gollum jumps into the water, off his boat,
to chase Bilbo. Bilbo runs away into the darkness and trips. He feels
the ring slip onto his finger and as Gollum passes by him he's
confused as to why he can't be seen.

Gollum worries that Bilbo will try to find a way out with his precious
ring and goblins will catch him; using the ring's power of
invisibility to their advantage and killing him.

** Escaping Gollum
Gollum unknowingly guides Bilbo near the exit trying to look for him
but stops short of where the Goblins tend to be. Bilbo tries to make a
daring escape and jumps over Gollum whose heightened senses perceive
him. But Gollum is unsuccessful in catching him. Bilbo keeps running
but Gollum stops and curses him, calling him a thief. Bilbo finds a
door.

** Escaping the goblins
Bilbo sees goblins by the door and they notice him as well. Somehow
the ring was no longer on his finger. They start rushing him and
instead of pulling out his sword he instinctively reaches in his
pocket, looking for the ring. He goes invisible and the goblins are
taken aback. They start searching for him as he hides behind a
barrel. After some time he braves an escape and swerves between the
goblins toward the door. He tries to slip through a crack left open in
the door but gets stuck, his buttons holding him back. The goblins
notice there is a shadow near the door which motivates Bilbo to push
through, bursting his buttons off his shirt in the attempt. Finally
he's outside.

* Chapter 6 - Out of the frying-pan into the fire
** Finding the crew
Bilbo realizes he's lost on the other side of the Misty Mountains and
he walks around for a bit. Eventually he hears some voices and
realizes its his group of allies. They're looking around for him but
can't see him as he's still wearing the ring of invisibility. He plans
to sneak up on them and reveal himself as a surprise but he overhears
the dwarves saying they should leave him behind. Gandalf angrily
disagrees and says Bilbo is useful to the group and that they should
go back and search for him.

** Bilbo reveals himself
Bilbo reveals himself to the group and they are amazed at his story of
how he escaped. He leaves out the detail of the ring but suspects
Gandalf knows he's hiding something.

** Onwards
Gandalf says the group needs to trek ahead as nightfall is coming and
the goblins will sure try to find them. Bilbo is hungry but they lost
all their supplies in the mountains when they were captured.

** Landslide and the clearing
They continue their way up the mountain and come across a landslide
that nearly takes them out. They manage to escape into the trees. They
came upon a clearing and suddenly the sound of wolves howling grows
closer.

** Hundreds of eyes
They all scramble up into trees but Bilbo is too small to find a
branch. Dorin tries to extend a hand but Bilbo is not able to grab it
so Dorin steps down and allows Bilbo to climb on his back. This helps
Bilbo get onto a branch just as hundreds on eyes appear in the
clearer. The eyes belong to wolves who are now rushing Dorin as he
manages to escape into the tree.

** The Wargs
The wolves are known as Wargs and they station guards at the foot of
Dorin and Bilbo's tree, sniffing for the others. Once they manage to
find all the occupied trees they station guards there as
well. Luckily, Wargs are not able to climb so for the moment the group
is safe.

There is a great wolf among the creatures who begins speaking to them
in their language.

** Overhearing the plan
We learn, from Gandalf listening to Wargs talking, that they are
allies of the goblins. They had both planned a raid against the humans
who are settled in the woods but are surprised the goblins haven't
arrived.

** Fire
Gandalf gathers some pine cones and sets them ablaze, throwing them
down into the Wargs and burning them. The Wargs run around yelping and
setting each other on fire.

From far above the Lord of the Eagles is watching, curious what is
happening. He sees the Wargs on fire and goblins marching in their
direction. He calls some other eagles to join him.

The goblins arrive and put out the burning Wargs. Then, they make a
huge fire underneath the dwarves and Gandalf, singing songs and
taunting them.

** Flying out of danger
Gandalf climbs to the top of his tree and the Lord of the Eagles
swoops down and grabs him. The dwarves are also grabbed by eagles and
Bilbo is almost left behind. He manages to grab onto Dori's leg as
they fly away.

Bilbo's arms are about to give out when they reach one of the nests
where he and Dori are placed. The eagle that grabbed them is told to
bring them to the rest of the group so he does.
** The agreement
When they arrive Gandalf is asking the Lord of the Eagles to take them
as far as they can out of the mountains which the Lord agrees. The
group eat some food and rest for the night.

* Chapter 7 - Queery lodgings
** Flying to the rock
Bilbo wakes up hoping he's at home but remembers he's with the eagles
and the group. He climbs on the back of an eagle and closes his eyes
as they start soaring into the sky.

Eventually, they come to a rock surrounded by a river where they are
dropped off. The eagles give a specific phrase farewell which Gandalf
returns with the correct phrase and the group make their way down and
across the river into a cave filled with with pebbles.

** The bear man
They learn that they are going to visit a man who lives at The
Carrock. This man can turn into a bear and shift into other forms. We
learn that Gandalf will soon leave them as he has other pressing
matters to attend to.

We learn that this man is quite particular about not eating meat, he
can talk to animals, and he gets upset easily.
